import { Router } from "express";
import { authenticate, requireRole } from "../middleware/auth.js";
import { validate } from "../middleware/validate.js";
import { createBiometricDeviceSchema, createOrgSchema, createPackageSchema, organizationAdminSchema, resetPasswordSchema, updateOrganizationAdminSchema, updatePackageSchema } from "../schemas.js";
import * as controller from "../controllers/platform.controller.js";

export const platformRoutes = Router();
platformRoutes.use(authenticate, requireRole("SUPER_ADMIN"));
platformRoutes.get("/dashboard", controller.dashboard);
platformRoutes.get("/audit-logs", controller.auditLogs);
platformRoutes.post("/organizations", validate(createOrgSchema), controller.createOrganization);
platformRoutes.patch("/organizations/:id/status", controller.updateOrganizationStatus);
platformRoutes.post("/organization-admins", validate(organizationAdminSchema), controller.createOrganizationAdmin);
platformRoutes.patch("/organization-admins/:id", validate(updateOrganizationAdminSchema), controller.updateOrganizationAdmin);
platformRoutes.patch("/organization-admins/:id/password", validate(resetPasswordSchema), controller.resetOrganizationAdminPassword);
platformRoutes.patch("/organization-admins/:id/status", controller.updateOrganizationAdminStatus);
platformRoutes.delete("/organization-admins/:id", controller.removeOrganizationAdmin);
platformRoutes.post("/packages", validate(createPackageSchema), controller.createPackage);
platformRoutes.patch("/packages/:id", validate(updatePackageSchema), controller.updatePackage);
platformRoutes.delete("/packages/:id", controller.deletePackage);
platformRoutes.post("/biometric-devices", validate(createBiometricDeviceSchema), controller.createBiometricDevice);
platformRoutes.patch("/biometric-devices/:id", controller.updateBiometricDevice);
